fixtures:
  symlinks:
    profile: "#{source_dir}/site/profile"
  repositories:
    node_encrypt:
      repo: "https://github.com/binford2k/binford2k-node_encrypt"
      ref: "d021a17d34e726affafa3290577a6da563b251b9"
    chocolatey:
      repo: "https://github.com/puppetlabs/puppetlabs-chocolatey"
      ref: "3.0.0"
    dsc:
      repo: "https://github.com/puppetlabs/puppetlabs-dsc"
      ref: "1.3.0"
    splunk: 'https://github.com/voxpupuli/puppet-splunk'
    staging: 'https://github.com/voxpupuli/puppet-staging'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile'
    powershell: 'https://github.com/puppetlabs/puppetlabs-powershell'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    ravendb: 
      repo: 'https://github.com/tragiccode/tragiccode-ravendb'
      ref: 'master'
    reboot:
      repo: "https://github.com/puppetlabs/puppetlabs-reboot"
      ref: "1.2.1"
    registry:
      repo: "https://github.com/puppetlabs/puppetlabs-registry"
      ref: "1.1.4"