fixtures:
  symlinks:
    profile: "#{source_dir}/site/profile"
  repositories:
    windows_ad: 'https://github.com/insentia/windows_ad'
    splunk: 'https://github.com/voxpupuli/puppet-splunk'
    staging: 'https://github.com/voxpupuli/puppet-staging'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile'
    powershell: 'https://github.com/puppetlabs/puppetlabs-powershell'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'